import React from "react";
import Head from "next/head";
import Image from "next/image";
import Header from "../header/Header";
import Footer from "../footer/Footer";

interface Props {
  children: React.ReactNode;
}

export default function MainContainer({ children }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      {children}

      <Footer />
    </>
  );
}
