import React from 'react';
import Head from 'next/head';
import Header from '../header/Header';
import Footer from '../footer/Footer';
import { MainContainerStyled } from '../../styles/components/layouts/MainContainer';

interface Props {
  title: string;
  children?: React.ReactNode;
}

export function MainContainer({ title, children }: Props) {
  return (
    <>
      <Head>
        <title>The Traveller | {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/globe.ico" />
      </Head>

      <Header />

      <MainContainerStyled>{children}</MainContainerStyled>

      <Footer />
    </>
  );
}
